<template>
  <div>
    <div class="nav gutter">
      <div class="nav-bar">
        <!-- Image Map Generated by http://www.image-map.net/ -->

        <a class="h1">新型冠状病毒疫情实时动态更新</a>
        <br>
        <a class="h2">网络一线牵，我与你同在</a>

      </div>
    </div>
    <router-view />
  </div>
</template>
<style>
.nav-bar {
  background-image: url("../assets/navv.jpg");
}
.h1 {
  font-size: 32px;
  color: aliceblue;
  margin-left: 135px;
  font-weight: 1000;
}
.h2 {
  font-size: 24px;
  color: aliceblue;
  margin-left: 135px;
}
</style>
